"""Structured Site Analysis models."""


from typing import Literal

from pydantic import BaseModel, ConfigDict


class StrictAnalysisModel(BaseModel):
    """Base model compatible with OpenAI strict structured outputs."""

    model_config = ConfigDict(extra="forbid")


class ContentSelector(StrictAnalysisModel):
    """Selector for one output field."""

    field: str
    selector: str
    attribute: str | None


class PaginationAnalysis(StrictAnalysisModel):
    """Detected pagination strategy."""

    type: Literal["none", "link", "numbered", "cursor", "infinite_scroll", "unknown"]
    selector: str | None
    url_pattern: str | None


class CrawlRecommendation(StrictAnalysisModel):
    """Recommended implementation strategy."""

    tool: Literal["httpx", "requests", "playwright", "api"]
    strategy: str
    notes: list[str]


class SiteAnalysis(StrictAnalysisModel):
    """Structured site analysis report generated by the LLM."""

    web_type: Literal["STATIC", "DYNAMIC", "API_BASED", "PAGINATED", "UNKNOWN"]
    content_selectors: list[ContentSelector]
    pagination: PaginationAnalysis
    challenges: list[str]
    recommendation: CrawlRecommendation
    rate_limit: float
