"""Structured Site Analysis models."""

from __future__ import annotations

from typing import Any, Literal

from pydantic import BaseModel, Field


class SiteAnalysis(BaseModel):
    """Structured site analysis report generated by LLM."""

    web_type: Literal["STATIC", "DYNAMIC", "API_BASED", "PAGINATED", "UNKNOWN"] = (
        "UNKNOWN"
    )
    content_selectors: dict[str, Any] = Field(default_factory=dict)
    pagination: dict[str, Any] = Field(default_factory=dict)
    challenges: list[str] = Field(default_factory=list)
    recommendation: dict[str, Any] = Field(default_factory=dict)
    rate_limit: float = 1.0
